### PR TITLE
Allow options passing through insert

### PR DESCRIPTION
**Pull request by Marsup**

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks!

**Comment by jonschlinkert** [comment]
0.7.0 published to npm. thanks again!

**Comment by Marsup** [comment]
You're welcome, thanks for the fast publish.

**Comment by Marsup** [comment]
Something seems to be broken in this release, my ToC is completely flat now, no subsections indentations.

**Comment by jonschlinkert** [comment]
@Marsup that should be fixed with the pr you did. Is everything working now?

**Comment by Marsup** [comment]
Confirmed.

**Comment by jonschlinkert** [comment]
:+1:

**Pull request merged**
