### PR TITLE
Pass options via CLI

### LINKED ISSUE #94: cli options
When using this in CLI mode it would be helpful if it supported more standard options.

A simple use case would be supporting the indent size from the CLI which is related to #87.

I am using this tool to generate the TOC for a document exported by IA Writer, the indents are wrong.

Thanks!

### PR DESCRIPTION
**Pull request by sapegin**
Supports all options except `filter`, `slugify` and `bullets` as an array (just a string is supported).

I’ll update the docs after code review.

Closes #94, #89.

### CODE REVIEW

**Comment by sapegin** [comment]
//cc @gregorskii @mjhm

**Comment by doowb** [comment]
@sapegin please remove the `package-lock.json`. Also, I think minimist can support arrays my specifying the argument multiple times. It might be fine the way you specified it to work, but if you try the following and it works, I think documentation is fine:

```sh
markdown-toc --bullet "*" --bullet "-" --bullet "+" input.md
```

Other than that, I think it looks good and if you want to update the `.verb.md` with the commandline documentation, one of us will build the readme when we merge.

**Comment by sapegin** [comment]
@doowb Yep, it works with array! I’ve updated the docs a bit.

**Comment by doowb** [comment]
Thanks!

**Pull request merged**
